version: 2
project_name: cli-replay

before:
  hooks:
    - go mod tidy

builds:
  - id: cli-replay
    main: .
    binary: cli-replay
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/cli-replay/cli-replay/cmd.Version={{.Version}}
      - -X github.com/cli-replay/cli-replay/cmd.Commit={{.Commit}}
      - -X github.com/cli-replay/cli-replay/cmd.Date={{.Date}}

archives:
  - id: default
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  use: git
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - "(?i)merge pull request"
      - "(?i)merge branch"
  groups:
    - title: "Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug Fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "Other Changes"
      order: 999

release:
  github:
    owner: ormasoftchile
    name: cli-replay
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"
